Upgrade pandas to 2.2.2
I was able to recreate the error in #32 when importing pandas locally using pandas v2.0.1 by running the folllowing:

```
$ pipenv run python
# ...
>>> import pandas
# ...
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Upgrading to 2.2.2 seems to fix it. Now I can run `import pandas` with any error.